config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'

  resources :users, only: [:index, :show]
  resources :teamcolors, only: [:index, :show]
  resources :cards, only: [:index, :show]

  resources :search, only: [:index] do
    collection do
      get 'results'
    end
  end

  #get 'pages/about', to: 'pages#about'
  get 'about', to: 'pages#about', as: 'about'


  # get 'teamcolor', to: 'teamcolors#index', as: 'teamcolor'
  # get 'card', to: 'cards#index', as: 'card'
  # get 'users/index'
  # get 'users' => 'users#index'
  # get 'users/show'
  # get 'users/:id', to: 'users#show', id: /\d+/
  # get 'teamcolors/index'
  # get 'teamcolors/show'
  # get 'cards/index'
  # get 'cards/show'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/card.rb
class Card < ApplicationRecord
  has_many :user_cards
  has_many :users, through: :user_cards

  validates :layout, presence: true
  validates :name, presence: true
end

app/models/teamcolor.rb
class Teamcolor < ApplicationRecord
    has_many :users, dependent: :destroy


    validates :color, presence: true, uniqueness: true
    
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :teamcolor
  has_many :user_cards
  has_many :cards, through: :user_cards

  validates :name, presence: true
  validates :username, presence: true
  validates :age, numericality: { only_integer: true }
  validates :user_level, presence: true, numericality: { only_integer: true }
end

app/models/user_card.rb
class UserCard < ApplicationRecord
  belongs_to :user
  belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  def index
    @cards = Card.all
  end

  def show
     @card = Card.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
    def about
        
    end


end

app/controllers/search_controller.rb
class SearchController < ApplicationController
    def index
    end

    def results
        @users = User.where('name LIKE ?', "%#{params[:q]}%")
    end
end

app/controllers/teamcolors_controller.rb
class TeamcolorsController < ApplicationController
  def index
    @teamcolors = Teamcolor.all
  end

  def show
     @teamcolor = Teamcolor.find(params[:id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
     @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/teamcolors_helper.rb
module TeamcolorsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cards/index.html.erb
<h1>Cards</h1>

<ul>
    <% @cards.each do |card| %>
    <li><%= link_to card.name, card %></li>
    <% end %>
</ul>

app/views/cards/show.html.erb
<h2>Details for: <%= @card.name %> </h2>

<p><b>Layout: </b><%= @card.layout %></p>
<p><b>Power: </b><%= @card.power %></p>
<p><b>Toughness: </b><%= @card.toughness %></p>

<p>List of users who have this card:</p>
<ul>
    <% @card.users.each do |user| %>    
    <li><%= link_to user.name, user %></li>
    <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IntroToRailsData</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="/assets/javascripts/search_helper.js"></script>
  </head>

  <body>
    <header>
      <h1>Intro to Rails Data Project</h1>
      <p>______________________________________________</p>
      <h4>
        <%= link_to "Home | ", root_path%>         
        <%= link_to "Team Colors | ", teamcolors_path%> 
        <%= link_to "Cards | ", cards_path%> 
        <%= link_to "About", about_path%> 
      </h4>
      <p>----------------------------------------------------------------------</p>
    </header>
    <%= yield %>
    <footer>
    <p>______________________________________________</p>
     <p>Student: Fabio Pereira</p>
    </footer>

  </body>
</html>

app/views/pages/about.html.erb
<h2> About my Intro to Rails Data Project </h2>

<p> This project consists in keep track of user's score who play <b>Magic: the Gathering </b> </p>
<p> The users are also separate by teams.  Each team is named by a <b>Color</b></p>
<p> Therefore, group of players can get together to play as divided group (if they wish to) and keep track of their <b>victory level</b>.</p>
<p> The data inserted came from the followed resources:</p>
<ul>
    <li>MTG Json - https://mtgjson.com/ - All Cards </li>
    <li>Gem Faker </li>
</ul>


<p> The ERD of this project:</p>
 <%= image_tag("ERD.png", :alt => "Project ERD") %>






app/views/search/index.html.erb
<h2> Search for Users </h2>

<%= form_tag(results_search_index_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/search/results.html.erb
<h2>Users Found: <%= @users.size %></h2>

<% if @users.empty? %>
    <p>Sorry, no user found.</p>
<% else %>
    <ul>
        <% @users.each do |user| %>
        <li><%= link_to user.name, user %> </li>
        <% end %>
    </ul>
<% end %>

app/views/teamcolors/index.html.erb
<h1>Team Colors</h1>

<ul>
    <% @teamcolors.each do |teamcolor| %>
    <li><%= link_to teamcolor.color, teamcolor %></li>
    <% end %>
</ul>

app/views/teamcolors/show.html.erb
<h2>List of users for the <i> <%= @teamcolor.color %> </i>team: </h2>

<ul>
    <% @teamcolor.users.each do |user| %>
    <li><%= link_to user.name, user %></li>
    <% end %>
</ul>

app/views/users/index.html.erb
<h1>Users</h1>

<%= form_tag(results_search_index_path, method: "get") do %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q, nil, {:onkeyup => 'quickSearch()'}) %>
  <%= submit_tag("Search") %>
<% end %>

<ul id="ul_search">
    <% @users.each do |user| %>
    <li><%= link_to user.name, user %>    (cards: <%= user.cards.count %>)</li>
    <% end %>
</ul>

app/views/users/show.html.erb
<h2> <%= @user.name %> </h2>

<p><b>Username: </b><%= @user.name %></p>
<p><b>Age: </b><%= @user.age %></p>
<p><b>User_level: </b><%= @user.user_level %></p>
<p><b>Team Color:</b> <%= link_to @user.teamcolor.color, teamcolor_path(@user.teamcolor.id) %></p>

<p>List of the cards owned by the user:</p>
<ul>
    <% @user.cards.each do |card| %>
    <li><%= link_to card.name, card %></li>
    <% end %>
</ul>

<%# controller: 'teamcolors', action: 'show' %>